### ISSUE TITLE
Not able to visualize the patches from custom area.

### ISSUE THREAD

**Issue by toniesteves** [sentinel-hub/eo-learn#143]
When I load a geojsom from another area I cannot display it in true colors, instead, an black image is displayed. I just change geojson region.

**Comment by mlubej** [comment]
Hi @toniesteves 

can you confirm that the CRS that you are using is the correct one? maybe you can also provide a minimum working example so we can take a look.

cheers

**Comment by Niraj-Lunavat** [comment]
I am also facing the same issue, I am uploading my [notebook](https://drive.google.com/open?id=1m1hYx2nE0iv4QzGf_Dt1BPy7yfiaY5_K) and [Geojson](https://drive.google.com/file/d/1Z12hZcNmiE9Zm5OKvBBmnmrGWRatq-He/view?usp=sharing) file

**Comment by Niraj-Lunavat** [comment]
@mlubej any clue....where I am doing wrong?

**Comment by mlubej** [comment]
It works fine for me, the only thing I did was that I removed the rasterization task, because you don't have any reference data of your own, and you shouldn't use the provided reference data in your case.
![image](https://user-images.githubusercontent.com/37869250/70030777-37063a00-15aa-11ea-8694-a759750bb3ae.png)

**Comment by Niraj-Lunavat** [comment]
can you please upload your notebook file

**Comment by mlubej** [comment]
Here you go
[pune.zip](https://github.com/sentinel-hub/eo-learn/files/3915463/pune.zip)

**Comment by Niraj-Lunavat** [comment]
How to create reference data of my own for custom area or where one get the refrence data?

**Comment by mlubej** [comment]
This is completely up to you. There can be something on the internet that you can use, maybe you can use some reference data provided by the government, or you can even create your own :)

**Comment by Niraj-Lunavat** [comment]
apart from Slovenia, do we have other location data, I am interested to run the same code with other locations. many Thanks

**Comment by gmilcinski** [comment]
You can try [France](https://aws.amazon.com/marketplace/pp/prodview-y5nwqeuw7porq?qid=1575729194426&sr=0-2&ref_=srh_res_product_title) or [Flanders](https://aws.amazon.com/marketplace/pp/prodview-u6bjmk6tkkngc?qid=1575729194426&sr=0-3&ref_=srh_res_product_title).

**Comment by Niraj-Lunavat** [comment]
anything from India or any scope to create @gmilcinski

**Comment by gmilcinski** [comment]
No, unfortunately not.

**Comment by azupanc** [comment]
I'm closing this issue since the discussion became non-technical and unrelated to eo-learn. The same discussion is ongoing in parallel on [SH forum](https://forum.sentinel-hub.com/t/how-to-slove-error-in-the-si-lulc-pipeline/1610). Please continue with the discussion on the forum so that all relevant feedback is collected in one place.
