### ISSUE TITLE
Error running Workflow: time_interval not found for S2L1CWCSInput

### ISSUE THREAD

**Issue by vatsalag99** [sentinel-hub/eo-learn#193]
Hi, 
I was working the Slovenia Landcover example for my own analysis. When I try running the full workflow, it gives this error: 

ValueError: During execution of task S2L1CWCSInput: Parameter time_interval was neither defined in initialization of S2L1CWCSInput nor is contained in EOPatch

I am passing the time_interval in the dictionary for the specific EOTask. 

I have attached the code below: 

```
time_interval = ('2017-01-01', '2017-12-31')
execution_args = []
for idx, bbox in enumerate(bbox_list[patchIDs]):
    execution_args.append({
        add_data:{'time_interval': time_interval},
        save: {'eopatch_folder': 'eopatch_{}'.format(idx)}
    })
workflow.execute({
        add_data:{'bbox': bbox, 
                  'time_interval': time_interval
                 },
        save: {'eopatch_folder': 'eopatch_{}'.format(idx)}
  })
```

and  

```
add_data = S2L1CWCSInput(
    layer='BANDS-S2-L1C', 
    feature=(FeatureType.DATA, 'BANDS'), # save under name 'BANDS'
    custom_url_params={CustomUrlParam.EVALSCRIPT: custom_script}, # custom url for 6 specific bands
    resx='10m', # resolution x
    resy='10m', # resolution y
    maxcc=0.8, # maximum allowed cloud cover of original ESA tiles
)
```

**Comment by mlubej** [comment]
Hi @vatsalag99,

the code for downloading data has changed, please check again the latest tutorial notebook and let us know if the issue persists.

BTW, if you define `execution_args`, you do not need to create the same thing again in `workflow.execute`, you can simply pass those `execution_args` as a parameter.

Closing the issue for now since the code is deprecated.
