### ISSUE TITLE
trouble with cloud mask in tutorial SI_LULC_pipeline

### ISSUE THREAD

**Issue by sbdelahaies** [sentinel-hub/eo-learn#198]
Dear eo-learn team,

first of all many thanks for this awesome package. I ran a couple of examples, most of them worked fine.

I am having trouble reproducing SI_LULC_pipeline: the mask IS_VALID contains only False values, cloud prob does not look at all as in the notebook, then ndvi_mean_clean gets only NaN values and so on.

I suspect the problem comes from the cloud_classifier or add_clm task but I can't figure out how to solve this issue, any idea?

Best regards

**Comment by devisperessutti** [comment]
Hello,

We'd need more details to find the issue (was the script changed?). We also updated the example to use the cloud masks provided through SentinelHub, so we recommend updating `eo-learn` to `0.7.4`.

**Comment by Rim-chan** [comment]
Hey, I have also faced the exact same problem and so far couldn't solve it

**Comment by mlubej** [comment]
Hi @Rim-chan,

I just ran the `master` version of the notebook and the cloud masks seem to get downloaded normally.  Even the execution report is all green:

![image](https://user-images.githubusercontent.com/37869250/84578136-c47cdf00-adc2-11ea-8d3a-a21efa5a10e6.png)

Can you check the output of the logs? Do you see any obvious errors? Did you make any changes to the version of the notebook?

Regards,
Matic

**Comment by Rim-chan** [comment]
Yeah, I tried to download the Sentinel 2-L2A data instead of L1C. 
However, with the L1C data, I noticed that the cloud masks are not detecting clouds when I tried to visualize cloud probability, RGB image, and cloud mask. I am not sure what I did wrong. So I tried to use this code: 
``
band_names=['B01','B02','B03','B04','B05','B06','B07','B08','B8A','B09','B10','B11','B12'] 
add_data = SentinelHubInputTask(
    bands_feature=(FeatureType.DATA, 'BANDS'),
    bands = band_names,
    resolution=10,
    maxcc=0.1,
    time_difference=datetime.timedelta(minutes=120),
    data_source=DataSource.SENTINEL2_L1C,
    additional_data=[(FeatureType.MASK, 'dataMask', 'IS_DATA')],)
                    # (FeatureType.MASK, 'CLM'),                           # 0 (no clouds), 1 (clouds), 255 (no data)
                    # (FeatureType.DATA, 'CLP')])                          # 0–255 (divide by 255 to get to the [0-1] range)


# TASK FOR CLOUD INFO
# cloud detection is performed at 80m resolution 
# and the resulting cloud probability map and mask 
# are scaled to EOPatch's resolution

cloud_classifier = get_s2_pixel_cloud_detector(average_over=2, dilation_size=1, all_bands=True)
cloud_detection = AddMultiCloudMaskTask(cloud_classifier, data_feature='BANDS', processing_resolution='80m',     #'BANDS-S2CLOUDLESS',
                                   mono_features=('CLP', 'CLM'))
 ``
Which results in the following error:
[file:///C:/Users/ASUS/Downloads/report%20(24).html](url) 
I can't figure this out. Am I using a wrong instance or something?

**Comment by mlubej** [comment]
Thanks for the details of your code. So if I understand correctly, you wanted to check the cloud info with the latest code, didn't manage to do it, and then wanted to check the output of the manually calculated cloud masks?

The code that you provided is actually not the right way to calculate cloud masks manually. You only need to do the following:

```python
band_names = ['B01', 'B02', 'B03', 'B04', 'B05', 'B06', 'B07', 'B08', 'B8A', 'B09', 'B10', 'B11', 'B12']
add_data = SentinelHubInputTask(
    bands_feature=(FeatureType.DATA, 'BANDS'),
    bands = band_names,
    resolution=10,
    maxcc=0.8,
    time_difference=datetime.timedelta(minutes=120),
    data_source=DataSource.SENTINEL2_L1C,
    additional_data=[(FeatureType.MASK, 'dataMask', 'IS_DATA')],
)

add_clm = AddMultiCloudMaskTask(data_feature='BANDS',
                                all_bands=True,
                                processing_resolution=160,
                                mono_features=('CLP', 'CLM'),
                                mask_feature=None,
                                average_over=16,
                                dilation_size=8)
```

which is also written in the notebook under cell 6. Did you miss this? If yes, then perhaps the placement of this information is not optimal and should be changed.

Before moving on to the problem with manually calculated masks, I wish to address the initial problem. You mentioned that 

> However, with the L1C data, I noticed that the cloud masks are not detecting clouds when I tried to visualize cloud probability, RGB image, and cloud mask

Could you expand on that? Can you show the code snippet how you wanted to visualize the information? Did the EOPatch content seem as expected?

**Comment by Rim-chan** [comment]
Thanks for the response !
I deleted the code from my notebook, as I was trying to figure things out and. But I posted the issue on StackExchange with the code and screen shots. Here is the link:
[https://gis.stackexchange.com/questions/364640/problem-with-sentinel-2-l2a-cloud-mask-and-valid-pixel-counts](url)

**Comment by mlubej** [comment]
The link doesn't seem to work for me.

BTW, manually calculating cloud masks ONLY works on L1C data, you should not apply it to L2A as it will not work. 

But if you use precomputed CLM and CLP bands from the service, you can download them along with L2A data as well.

**Comment by Rim-chan** [comment]
> But if you use precomputed CLM and CLP bands from the service, you can download them along with L2A data as well.
I tried this as well, but it didn't detect the majority of clouds. 
BTW, are the precomputed CLM and CLP are computed using S2Cloudless or Sen2core?

**Comment by mlubej** [comment]
> I tried this as well, but it didn't detect the majority of clouds.

Ah, I see. I saw on your stack issue that you had issues detecting smaller clouds. The precomputed CLM is averaged on 160m and smaller clouds seem to go unnoticed. What you could try in this case is visualize CLP > 0.4, which is the default what s2cloudless uses. This might give you more accurate cloud masks in case of smaller clouds.

> BTW, are the precomputed CLM and CLP are computed using S2Cloudless or Sen2core?

In order to precompute CLM and CLP we used s2cloudless, but very slight differences may occur, depending on your usage. More info [here](https://docs.sentinel-hub.com/api/latest/#/API/data_access?id=cloud-masks-and-cloud-probabilities).

> Why is that, If I may ask.

The s2cloudless classifier is a machine learning-based classifier which was trained on only L1C data. We decided to use the raw form of the bands since L2A is obtained by applying some process on L1C anyway. Since the L2A values differ from L1C, the ML classifier doesn't recognize the patterns and the results probably don't make sense in that case.

**Comment by Rim-chan** [comment]
> What you could try in this case is visualize CLP > 0.4, which is the default what s2cloudless uses. This might give you more accurate cloud masks in case of smaller clouds.

I don't think I understand what you mean here. Could you please elaborate on that?

**Comment by mlubej** [comment]
The s2cloudless classifier produces two outputs:
- the cloud pseudo-probabilities, which are available as the `CLP` band
- the cloud masks (`CLM`), which are the result of thresholding the cloud pseudo-probabilities + some postprocessing

One is usually interested in the cloud masks (so `CLM`), but you can also use the raw probabilities (`CLP`) to obtain the mask, however, due to different options for post-processing, the resulting mask may vary.

The postprocessing currently used in the Sentinel Hub service is more targeted towards larger clouds, so smaller clouds tend to go undetected. If you want to focus on smaller clouds, you can use the cloud probabilities directly.

If you look at the image that you posted:

https://i.stack.imgur.com/ob96A.png

you can see that `CLP` cloud probabilities pick up on the clouds, but the `CLM` mask does not, so using the `CLP > 0.4` as a custom mask might work better in your case.

In case you are not interested in optimizing CPU and aren't aiming at doing things "quick & dirty", I would suggest that you calculate cloud masks manually yourself, as explained in comment https://github.com/sentinel-hub/eo-learn/issues/198#issuecomment-643675497.

**Comment by mlubej** [comment]
I believe the issue was resolved or at least the info to solve it was provided. Closing the issue for now.
