### ISSUE TITLE
mosaicking_order attribute seems not working

### ISSUE THREAD

**Issue by fatal69100** [sentinel-hub/eo-learn#208]
Hi, 
I am trying to use the **_mosaicking_order_** for a _SentinelHubInputTask_. However, changing his value doesn't seems to affect the order in my EOPatch.
Does it sounds like a bug or is there another way to get the least Cloud coverage patch over a period of time ?
Thank you in advance for your help.

**Comment by mlubej** [comment]
Hi @fatal69100,

based on [this documentation](https://docs.sentinel-hub.com/api/latest/#/data/Sentinel-2-L1C?id=mosaickingorder), `mosaickingOrder` is used when mosaicking ESA tiles per orbit or per time interval (`ORBIT` or `SIMPLE`, as shown [here](https://docs.sentinel-hub.com/api/latest/#/Evalscript/V3/README?id=mosaicking)).

The `SentinelHubInputTask` input task works a bit differently. You have the `time_difference` parameter and the `single_scene` parameter.

If the `single_scene` parameter is set to `True`, all the data in the given time interval will be merged together based on the `mosaicking_order` that you provide. The output will be a single image.

If the `single_scene` parameter is set to `False`, the mosaicking will happen according to the `time_difference` parameter. If the `time_difference` parameter is very small (i.e. order of hours), then all images that you obtain will basically be separate tiles, but if it's large (a few weeks or more), all the acquisitions which fall into the same group based on the `time_difference` parameter will be merged together.

Whenever the mosaicking is applied, the default 'SIMPLE` way of stitching is used.

So when you use the `mosaicking_order` in the `SentinelHubInputTask`, it probably doesn't have any effect, since the `time_difference` that you use is probably `None`. This will NOT affect the order of the images in the `EOPatch`, as the images are always chronologically ordered.

Regarding the second part of your question, each ESA tile has the `maxcc` metadata, but this is not on the `EOPatch` level. What you are after is the cloud coverage of separate images inside the EOPatch`. You can obtain these values by running the cloud detector over the `EOPatch`, or download the `CLP` or `CLM` cloud probability/mask bands from Sentinel Hub. More information on how to do that can be obtained [here](https://docs.sentinel-hub.com/api/latest/#/API/data_access?id=cloud-masks-and-cloud-probabilities)

If you have any other questions, don't hesitate to ask. :)

Cheers

**Comment by mlubej** [comment]
Closing.
