### ISSUE TITLE
Due to the maxcc filtering, not all patches have the same amount of timestamps.

### ISSUE THREAD

**Issue by Arraystud** [sentinel-hub/eo-learn#213]
Dear Developers, 

The title already explains a large part of my question: Due to the maxcc filtering, not all patches have the same amount of timestamps. As a solution you make use of nearest timestamp. For my research I am working with river data and thus only interested in availability of timestamps on all patches at the same time. How can I filter out the differences? For example patch 1 contains 60 timestamps and patch 2 40 but I am only interested in the matching timestamp. Thanks in advance!

**Comment by mlubej** [comment]
Hi @Arraystud,

this is by design. Even without maxcc filtering, the number of timestamps might not be the same, because of the location. The larger the area, the larger the differences in available observations, because the satellite is not present in all locations at the same times.

There are a few things you can do:

- you can load all eopatches and find the intersection of all the timestamps. Probably not all of them are exactly the same, so perhaps it's better to reset the time of day and just use the date. After you have the dates which are available in all the eopatches, you can then do some filtering. The filtering can be manual, or you can write your own EOTask where you specify the dates that you want to keep

- still, the above will not work if your area is very large. In this case, I suggest that you apply interpolation (linear, nearest, etc) and obtain the values at specific dates. This way you can make sure that the data will be uniform and the closest valid values to the specified frames will be used.

You can check out how to do the interpolation in the land cover tutorial.

**Comment by Arraystud** [comment]
Hi @mlubej,

Thank you for your clear answer. My area of interest is not very large so I would like to try to focus on your first solution which is finding an intersection of these patches. Could maybe give me an example on how to start on this? I haven't got a clue on where to start.. Thanks again.

**Comment by mlubej** [comment]
> Could maybe give me an example on how to start on this?

You could try something like this:

```python
# lazy load all eopatches
eop_locations = ['path_to_eop1', 'path_to_eop2', 'path_to_eop3', ...]
eopatches = []
for loc in eop_locations:
    eop = EOPatch.load(loc, lazy_loading = True)
    eopatches.append(eop)

# create sets of timestamps
sets = [set([ts.date() for ts in eop.timestamp]) for eop in eopatches]

# loop through eop timestamps, keep only intersections
dt_list = sets[0]
for i in range(1,len(sets)):
    dt_list = dt_list.intersection(sets[i])

# convert to array, sort
dt_list = np.array(list(dt_list))
dt_list = np.sort(dt_list)
```

From this point on, you can use this list of `datetime` objects to select the dates nearest to the dates inside the EOPatch or you can even create a simple filter EOTask. Look inside the land-cover notebook for some direction on the Simple Filter task perhaps.

**Comment by Arraystud** [comment]
This is really helpful! So if interested in a simple filter EOTask, something like this could be used? 

> filter_task2 = SimpleFilterTask((FeatureType.TIMESTAMP), dt_list)

**Comment by mlubej** [comment]
No, unfortunately not. The `SimpleFilterTask` is just a task that filters based on some logic that you need to implement. It accepts a filter function that you need to define yourself.

You could implement something like:

```python
from functools import partial
from datetime import timedelta

def dt_list_filter(date, date_list, tolerance):
    return np.min(np.abs(date - np.array(date_list))) < tolerance

ftask = SimpleFilterTask(feature=FeatureType.TIMESTAMP, 
                         filter_func=partial(dt_list_filter, date_list=new_dates, tolerance=timedelta(days=1)))

new_eop = ftask(eop)    
```

This should filter your new patches to the desired timestamps, taking some tolerance into account.

**Comment by Arraystud** [comment]
Niceee you just saved the day. Could be more grateful. Thank you for your quick reply and help.
