### ISSUE TITLE
For any different geojson files, Tree_cover loss is showing error that data doesnot exit.

### ISSUE THREAD

**Issue by visalikk** [sentinel-hub/eo-learn#248]
For any different geojson files, Tree_cover loss is showing error that data doesnot exit. However i am able to filter down the data for the same geojson from sentinel hub EO browser. 
[shp78.zip](https://github.com/sentinel-hub/eo-learn/files/5184161/shp78.zip)
Please help

**Comment by mlubej** [comment]
Hi @visalikk,

when you changed the geojson files, did you also set the CRS to the appropriate one?

Can you provide an example of a geojson file and a notebook which you use (or the changes you did) where the combination fails? At which point does the error occur?  Can you copy-paste the stack trace of the error you get? Please provide more information so we can help you the best we can.

**Comment by visalikk** [comment]
Hi Matic, 

I am able to execute the code for eastern_france geojson file. But want to try for different geojson(polygon) . CRS i have used same code similar to eastern_france.  Do i need to change any? 

Geojson file: 
{"type":"FeatureCollection","features":[{"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[113.24375478399179,-7.7398640145810305],[113.24262334460764,-7.739443213395646],[113.24212193213805,-7.740810102780813],[113.24312249105697,-7.7413693519476965],[113.24320009030646,-7.741165098620002],[113.24375478399179,-7.7398640145810305]]]}}]}

notebook:  used the same 
https://github.com/sentinel-hub/eo-learn/blob/develop/examples/tree-cover-keras/tree-cover-keras.ipynb

Error line:  while executing workflow
idx = 168 
example_patch = execute_workflow(idx) 

Error:  
~/anaconda3/envs/tensorflow2_p36/lib/python3.6/site-packages/eolearn/io/processing_api.py in get_available_timestamps(bbox, config, data_source, maxcc, time_difference, time_interval)
     37 
     38     if len(dates) == 0:
---> 39         raise ValueError("No available images for requested time range: {}".format(time_interval))
     40 
     41     dates = sorted(dates)

ValueError: During execution of task SentinelHubInputTask: No available images for requested time range: ('2019-01-01T00:00:00', '2020-09-07T23:59:59') 

but for thr same polygon in EO browser i am able to see L2A images.  Have configured L2A true color in Sentinelhub instance. 


Thanks,
Visa

**Comment by mlubej** [comment]
Dear @visalikk,

the geojson file that you provide does not make any sense to me. The geojson used in the example is in WGS84 CRS, but when I load the one that you provide it does not make sense. What is the exact CRS code that you use? Perhaps this is the issue here.

**Comment by visalikk** [comment]
I am very new to the geo space but more eager to learn.The below is the lat long details for the attached geojson. how to convert this to WGS84 ?  I got a shp file which have got 127 polygons. I have split it into multiple geojsons.  It lat long details is as below  

Province | Districts | Sub_distri | Village | Latitude | Longitude | Area_Ha | Land_status | Remark
East Java | Probolinggo | Dringu | Dringu | 7° 44'   25,397" S | 113° 14'   49,432" E | 2.17 | Community Land | First Priority planting

**Comment by mlubej** [comment]
Dear @visalikk,

things make more sense now. I apologize, your shapefile is completely fine. The problem is that you probably unintentionally provide the wrong CRS to the reprojection and/or the bbox splitter.

It is best to transform to the natural UTM zone of the area so that you have a good estimate of the area size in meters. In your case this is `UTM_49S` (https://mangomap.com/robertyoung/maps/69585/what-utm-zone-am-i-in-#)

You can load your whole shapefile to the notebook and convert it to this CRS:

```python
crs = CRS.UTM_49S
aoi = geopandas.read_file('.../shp_priority_planting/Priority_Planting.shp')
aoi = aoi[aoi.Village == 'Dringu']
aoi = aoi.to_crs(crs=crs.pyproj_crs())
aoi_shape = list(aoi.geometry.values)
```
Here I limited the shapefile to the Dringu Village, then I transformed it into the UTM_49S and lastly, I put the geometries into a list.

![image](https://user-images.githubusercontent.com/37869250/93056639-fd03b180-f66c-11ea-8bea-84f2c0514dae.png)


Now you can put this to the BBox splitter so that we can decide on the splitting size. Let's start with just one eopatch:

```python
bbox_splitter = BBoxSplitter(aoi_shape, crs, (1, 1))
x1,y1,x2,y2 = bbox_splitter.bbox_list[0].geometry.bounds
print(x2-x1, y2-y1)
```
The output shows the dimensions of the bbox and is equal to: 1356.205903009628 1321.8467920664698, which means that the bbox spans about 1350 m in x and y direction. This is not a lot - at 10 m resolution of S2, this is about 130x130 pixel image, so it does not make sense to split it further. The same can probably be said for the other villages. Splitting is usually necessary when dealing with really large areas.

Running the SH input task on such an area results in a RGB color of this image:

![image](https://user-images.githubusercontent.com/37869250/93056961-77cccc80-f66d-11ea-9eaf-84949f8a98bf.png)

Which makes sense, since the area is in the water part

![image](https://user-images.githubusercontent.com/37869250/93057003-861ae880-f66d-11ea-82e8-963657c61c59.png)


Hope this helps!

Cheers,
Matic

**Comment by visalikk** [comment]
Thanks Matic. This helps a lot.  Let me try for the same Dringu village and roll out to other AOI's.

**Comment by mlubej** [comment]
Hi @visalikk,

> One silly question Matic, this resultant image is coming as shape (132,136,3) however the UNET train model defined need image of (256,256,3).. How can we resize from smaller size to bigger size. resize function is very easy in CV2 however i am very unaware of how to resize these geo images. Some guidelines please.

I'm not sure if this is the best idea because you would be augmenting the data this way. Check the original notebook - it uses a much larger area and the unet can then be applied on the eopatches.

If you don't want to retrain and just want to use the same model from the examples, I would suggest using the `UtmZoneSplitter` (see example [here](https://nbviewer.jupyter.org/github/sentinel-hub/sentinelhub-py/blob/master/examples/large_area_utilities.ipynb#Splitting-into-UTM-grid-zones))

You can specify the size of the bbox and set it to 256x256 and then apply the model on each eopatch.
