### ISSUE TITLE
[BUG] Wrong link in docs

### ISSUE THREAD

**Issue by maximlamare** [sentinel-hub/eo-learn#262]
**Wrong link in documentation**

In the documentation example showing how to create a Time Lapse: `TimeLapse.ipynb`, the link to the notebook (top right of the page) is the following: [Edit on Github](https://github.com/sentinel-hub/eo-learn/blob/master/docs/source/examples/core/TimeLapse.ipynb)

This link sends to a `404 not found` page. 

**Expected behavior**

A link to the notebook: https://github.com/sentinel-hub/eo-learn/blob/master/examples/core/TimeLapse.ipynb

**Stack trace or screenshots**

![Screenshot from 2020-11-10 14-24-45](https://user-images.githubusercontent.com/32132761/98679566-84655c80-2360-11eb-88e1-70b75015c2f3.png)

**Comment by AleksMat** [comment]
There are quite a few pages in eo-learn documentation where this link doesn't work. It is because of the way we build documentation:

- example notebooks are first copied from examples folder to docs folder,
- some pages are generated from other content.

Because of that Sphinx generates these link with the new paths instead of original. Fixing this would require some research in Sphinx functionalities.

**Comment by zigaLuksic** [comment]
This was actually fixed by @AleksMat a while ago by employing some dark sphinx magic
