### ISSUE TITLE
SentinelHubInputTask  support for sentinelhub.Geometry

### ISSUE THREAD

**Issue by sanjivjha** [sentinel-hub/eo-learn#267]
Currently SentinelHubImputTask support sentinelhub.BBox for fetching data. It should also support sentinelhub.Geometry to support polynomial.

**Comment by mlubej** [comment]
Hi @sanjivjha,

thanks for this suggestion. It would be cool if geometry could be provided, where the data outside of the geometry would be masked automatically masked out, but since `eo-learn` focuses more on larger areas, this wasn't implemented.

One thing you could do, though:
1. use the `geometry.envelope` as your bbox
2. download data
3. import geometry vector and turn it to a raster with the `Vector2Raster` task in `eo-learn` to calculate the geometry mask, which you can then apply to the data.

If you are willing to extend the `SentinelHubInputTask` yourself with a PR, we would be very grateful! :) 

Cheers!

Matic

**Comment by zigaLuksic** [comment]
this was added in https://github.com/sentinel-hub/eo-learn/pull/461
The user must still provide a BBox, but we decided it should stay that way for now.
