### ISSUE TITLE
[HELP]

### ISSUE THREAD

**Issue by viajerus** [sentinel-hub/eo-learn#270]
Hi!
I tried to run this [Jupyter Notebook](https://github.com/sentinel-hub/eo-learn/blob/develop/examples/batch-processing/how_to_timelapse/how_to_timelapse.ipynb). Before I started the process, I carefully installed the required packages and got my credentials. When I execute the last chunk of code, I get the following error: **FileNotFoundError: During execution of task Animate: [WinError 2] The system cannot find the file specified**. It appears to be a major issue with the paths, since many of them are hardcoded for Linux. 

I would be very grateful if you could help me :)

Kind regards, 
Daniel 

PS: I work with Windows and Python 3.7.9

**Comment by mlubej** [comment]
Hi @viajerus !

Thanks for showing interest in the notebook. As you already correctly pointed out, the notebook is hardcoded for Linux, yes..

If this is just an issue with paths, perhaps you can just use the proper slash notation, or even better, to use

```python
import os
os.path.join('a', 'b', 'c')
```
in order to properly concatenate parts of the system path with respect to the system you are using.

I hope that helps for now. If it does, feel free to make an update PR yourself, otherwise I'll update the notebook in the near future.

Thanks for pointing out the issue!

**Comment by viajerus** [comment]
Hi @mlubej !
Thank you for the hint. I will try it out and see what else needs to be fixed. 

Best wishes, 
Daniel
