### ISSUE TITLE
How to get bands from custom area.

### ISSUE THREAD

**Issue by GalacticF** [sentinel-hub/eo-learn#28]
I'm trying to get S2-L1C bands for custom area with slightly changed code from examples directory.

```
input_task = S2L1CWCSInput('TRUE-COLOR-S2-L1C', resx='10m', resy='10m', maxcc=0.8, instance_id=INSTANCE_ID)
workflow = LinearWorkflow(input_task)
time_interval = ['2017-01-01','2017-12-31']
from sentinelhub import WebFeatureService, BBox, CRS, DataSource
bbox = BBox(bbox=[ 150.6450033,-32.4219569,150.6583071,-32.4383657], crs=CRS.WGS84)

results = workflow.execute({input_task:{'bbox':bbox, 'time_interval':time_interval}})
```
but got an Error: 
Server response: "Layer TRUE-COLOR-S2-L1C not found"

Is there any way to do?

**Comment by mlubej** [comment]
Hi @GalacticF!

Is the `TRUE-COLOR-S2-L1C` layer defined in your [configuration utility panel](https://apps.sentinel-hub.com/configurator/#/)?

Cheers

**Comment by gmilcinski** [comment]
You get this error because your Sentinel Hub instance does not have a layer with this specific ID. 
In case you are working with default (exemplary) instance, you can try with layer ID named "TRUE_COLOR".
To work efficiently with sentinelhub-py, we recommend to create a new instance using "Python scripts template":

1. Go to Configuration utility (https://apps.sentinel-hub.com/configurator/)
2. Click "Add new configuration"
3. Choose "Python scripts template"
4. Use new instance's ID in the scirpt.

<img width="730" alt="screenshot 2018-11-01 at 16 39 36" src="https://user-images.githubusercontent.com/16798351/47862251-fd865c80-ddf4-11e8-91d9-3ffee1105ea4.png">

**Comment by GalacticF** [comment]
@gmilcinski It works, thank you!
