### ISSUE TITLE
[FEAT] VectorToRaster time-dependent support

### ISSUE THREAD

**Issue by asylve** [sentinel-hub/eo-learn#301]
**What is the problem? Please describe.**

I needed to convert time-dependent geopandas vector data to raster images for an image masking project. As noted in the docs for eolearn.geometry.transformations.VectorToRaster, rasterization of time-depended features is not yet supported. 

**Here's the solution**

In my project I solved this by looping over each time step in the vector data, using VectorToRaster to store the result in MASK_TIMELESS['TEMP'], retrieving this and storing in a numpy array, then finally adding the numpy array to MASK['TIMED_MASK']. See below:

```
times, length, width, channels = eopatch.data['BANDS'].shape #get the required shape of the masks
timed_mask = np.zeros(shape=(times, length, width, 1), dtype=np.int16) #this will hold the rasterized masks

for vector_mask in vector_masks:
    add_raster = VectorToRaster(vector_mask, (FeatureType.MASK_TIMELESS, 'TEMP'),
                                    values_column='CT', raster_shape=(FeatureType.DATA, 'BANDS'),
                                    raster_dtype=np.int16)
    add_raster(eopatch)
    timed_mask[count] = eopatch.mask_timeless['TEMP'] #append the resulting raster image to our numpy array
            
eopatch.mask['TIMED_MASK'] = timed_mask #store the numpy array in the eopatch mask feature
```

Would it make sense to extend this functionality into VectorToRaster, so that a geopandas dataframe with a 'time' column could be passed in, and the resulting set of raster features would be passed into the eopatch? I would be happy to give this a try if it makes sense.

**Comment by AleksMat** [comment]
Hi @asylve,

I agree with the proposed extension of `VectorToRaster` task. We'll be happy to accept any pull request regarding that.

Each time-dependent vector feature already has to have a column named `'TIMESTAMP'`, therefore the task should group entries according to this column and rasterize them into a time-dependent raster feature. If an EOPatch already has a list of timestamps then the task should rasterize according to them, otherwise it should probably add them.

P.S. Sorry for the late answer.

**Comment by asylve** [comment]
Thanks, I'm glad you agree with the concept. I will start working on it.
