### ISSUE TITLE
[HELP]problem importing S2L1CWCSInput from eolearn

### ISSUE THREAD

**Issue by m0rp43us** [sentinel-hub/eo-learn#313]
i am trying to run notebooks from this repo : https://github.com/simongrest/farm-pin-crop-detection-challenge

here is the error i encountered : 

 in
22 from eolearn.core import EOTask, EOPatch, LinearWorkflow, FeatureType, OverwritePermission,
23 LoadFromDisk, SaveToDisk, EOExecutor
---> 24 from eolearn.io import S2L1CWCSInput, ExportToTiff
25 from eolearn.io.local_io import *
26 from eolearn.mask import AddCloudMaskTask, get_s2_pixel_cloud_detector, AddValidDataMaskTask

ImportError: cannot import name 'S2L1CWCSInput' from 'eolearn.io'

i don't know if it's a versioning problem or if the Method is no longer implemented there.

NEED HELP ASAP.

THANKS IN ADVANCE

**Comment by AleksMat** [comment]
Hi @m0rp43us,

Tasks that use Sentinel Hub WMS/WCS service, including `S2L1CWCSInput`, were removed in `eo-learn` version `0.9.0`. They were fully replaced by tasks `SentinelHubInputTask` and `SentinelHubEvalscriptTask`, which in the background use a newer Sentinel Hub Process API. The reason for removal is that because of the changes in evalscript definitions it became impossible to ensure that tasks that use use WMS/WCS service will download correct data.

I recommend checking:
- [this example notebook](https://eo-learn.readthedocs.io/en/latest/examples/io/SentinelHubIO.html) to see how to use the new tasks,
- [documentation page](https://eo-learn.readthedocs.io/en/latest/eolearn.io.sentinelhub_process.html) of these new tasks.

**Comment by m0rp43us** [comment]
that solved the problem,thanks !

**Comment by Tylerjoe** [comment]
> that solved the problem,thanks !

how did you solve this problem, could you please give a help

thanks a lot

**Comment by mlubej** [comment]
> > that solved the problem,thanks !
> 
> how did you solve this problem, could you please give a help
> 
> thanks a lot

Hi @Tylerjoe,

the previous user was referring to the nicely summed up solution in the comment above: https://github.com/sentinel-hub/eo-learn/issues/313#issuecomment-879824445

> Hi @m0rp43us,
> 
> Tasks that use Sentinel Hub WMS/WCS service, including `S2L1CWCSInput`, were removed in `eo-learn` version `0.9.0`. They were fully replaced by tasks `SentinelHubInputTask` and `SentinelHubEvalscriptTask`, which in the background use a newer Sentinel Hub Process API. The reason for removal is that because of the changes in evalscript definitions it became impossible to ensure that tasks that use use WMS/WCS service will download correct data.
> 
> I recommend checking:
> 
>     * [this example notebook](https://eo-learn.readthedocs.io/en/latest/examples/io/SentinelHubIO.html) to see how to use the new tasks,
> 
>     * [documentation page](https://eo-learn.readthedocs.io/en/latest/eolearn.io.sentinelhub_process.html) of these new tasks.
