### ISSUE TITLE
Free R&D accounts

### ISSUE THREAD

**Issue by gmilcinski** [sentinel-hub/eo-learn#35]
Please mention possibility to get free R&D account at this link:
https://earth.esa.int/aos/OSEO

This should be added somewhere here:
In order to run the example you'll need a Sentinel Hub account. You can get a trial version here.

**Comment by AleksMat** [comment]
This was added a while ago [here](https://eo-learn.readthedocs.io/en/latest/examples/land-cover-map/SI_LULC_pipeline.html#Requirements).

In the future we might instead of this paragraph just add link to `sentinelhub-py` documentation chapter with the same content. But for now I am closing the issue.
