### ISSUE TITLE
[FEAT] FeatureType.DATAFRAME prettypleasewithcherryontop

### ISSUE THREAD

**Issue by mlubej** [sentinel-hub/eo-learn#402]
**What is the problem? Please describe.**

I'm running a mowing algorithm which produces rich information for each pixel. This information cannot be described with the current features. You have a different amount of events for each pixel, different kinds of info and events are time intervals, not single dates.

**Here's the solution**

Would it be possible to add a dataframe feature type, so that I could save this info-rich dataframe to the eopatch? This way I could extract some info from the dataframe into the existing feature types, but still keep the original to do with it whatever I want. 

**Alternatives**

Currently this is possible only by pushing the dataframe to the metadata.

**Additional context**

We have an algorithm which works on dataframes and produces dataframes. We want to use the eo-learn/eo-grow functionality to run the process over eopatches, but keep the algorithm function as is.

**Comment by mlubej** [comment]
Some more info: 
- dataframes have a `.to_json` method, so it's possible to convert the info to JSON serializable content without much effort
- I tried adding the jsonified dataframe to the eopatch metainfo and it worked, saving it to disk also works
- the only issue was when I print out the eopatch, it tries to show all the dataframe content, which can be quite long. A dedicated feature could handle this nicely with its own `repr` function

**Comment by AleksMat** [comment]
@mlubej, have you tried using a vector or vector timeless feature for this? These feature types use geodataframes.

**Comment by AleksMat** [comment]
Hm, without geometries you can then just use non-spatial raster features (temporal/timeless scalar/label). This means that you will probably have to write each column of a dataframe into a different feature. Depending on how many columns you have you might get a lot of features but at least serialization will be efficient.

I suggest you try avoiding writing things into meta_info feature. Because your dataframes seem to be huge it would be too inefficient to serialize them as jsons.

**Comment by mlubej** [comment]
I'd say this is not so relevant anymore. closing.
