### ISSUE TITLE
SI_LULC_pipeline notebook 

### ISSUE THREAD

**Issue by mertensu** [sentinel-hub/eo-learn#491]
Hi, I am new to geo-spatial data analysis and was going through your _Land use and Land cover_ example. 

Two things that are not clear to me:

1) Where do you get the geojson file with the slovenian boundaries from? On the Natural Earth homepage, it seems one can only download a .shp file. 

2) How do you get the center patch ID (616)? And are you sure this is still correct? I run into: "Warning! Use a different central patch ID, this one is on the border."

Thanks in advance for your help!

**Comment by zigaLuksic** [comment]
1. The description states that we took the shape from the Natural Earth (as a .shp), then loaded the shape, applied a 500m buffer and saved it. You can find it in the repo under `example_data/svn_border.geojson`
2. In the cell where the selection is visualized you can also see which cell the corresponding ID belongs to. The ID 616 was chosen since the area contains all of the main landcover classes. I just re-rean the notebook and don't get an error, did you perhaps change something?

**Comment by zigaLuksic** [comment]
Also, feel free to report any oddities you find, we're always keen to improve the examples

**Comment by zigaLuksic** [comment]
Sounds like you should double-check that the CRS match, yes

**Comment by mertensu** [comment]
Actually the CRS matches. Did not change anything compared to the Slovenia example. 

`country = country.to_crs(epsg=32633).buffer(500)`

Plotting the `bbox_gdf` looks weird...

<img width="251" alt="image" src="https://user-images.githubusercontent.com/1891442/195159911-d3465d3f-56e6-4246-a620-0f62857a9457.png">

**Comment by zigaLuksic** [comment]
The notebook uses `UtmZoneSplitter` so for large countries you'll get the bboxes with different CRS (corresponding to the appropriate UTM zone, see [here](https://sentinelhub-py.readthedocs.io/en/latest/examples/large_area_utilities.html#Splitting-into-UTM-grid-zones)). The notebook assumes that all the BBoxes share the same CRS when the geodataframe is constructed.

**Comment by mertensu** [comment]
Thanks! And is there an easy way to circumvent this problem of different CRS and still get the same result?

**Comment by zigaLuksic** [comment]
Working over multiple CRS brings a whole set of issues. However for this example I believe you should only have problems when displaying results (the bbox_gdf seems to only be used for plotting purposes). 
Another angle is also that here we focus on only 9 EOPatches, partially to conserve data, and also because we the LGBM model for predictions we don't need to have an enormous amount of data. So you can just focus on a sub-area of Germany in order to run this notebook.

**Comment by zigaLuksic** [comment]
Assuming it was resolved due to inactivity
