### ISSUE TITLE
[HELP] Where has eopatch_to_dataset gone?

### ISSUE THREAD

**Issue by idantene** [sentinel-hub/eo-learn#636]
**Question**

In #83, the `eopatch_to_dataset` function was introduced.  
Somewhere since then, it was removed, and it begs the question why? The spatiotemporal aspect of the eopatch features lends itself very nicely to `xarray` and `rioxarray`, so it's a bit odd this conversion is not offered anymore.

Some of the history dig-up I've done includes:
- `utilities.py` was renamed and moved in #371 
- Even then, the code was not available
- Somehow, in v1.3.1 it was still importable from that location (IIRC the import location at least), but it was officially removed in 1.4.0
- In fact, while `xarray` is a dependency, it's no longer imported/used directly anywhere in the code, it seems

**Comment by zigaLuksic** [comment]
Hi @idantene 
I assume you are talking about the function that converts eopatches to xarray datasets?

It was used only in the `hvplot`-backend visualization, which broke during the last two years (and we weren't able to fix it). With the addition of the `matplotlib`-backend for visualization we decided to abandon the old approach in [version 1.4.0](https://github.com/sentinel-hub/eo-learn/releases/tag/v1.4.0) (see note about hvplot backend being removed).

Since then `xarray` should also no longer be a dependency of any kind.

**Comment by idantene** [comment]
That makes sense, thanks for the recap!

Wouldn't you agree though that such conversion methods benefits the eolearn package as a whole, providing streamlined interoperability with pandas and xarray, which are core tools in the data scientist tool box?

**Comment by zigaLuksic** [comment]
I do agree, and these are my thoughts on the situation:
1. if such features exist, they shouldn't be hidden away in visualization utilities. One should also be mindful of dependencies, `eolearn` is already far from _slim_
2. we very rarely use `xarray` so we never felt the need for such a converter, while `pandas` does not scale well (our projects frequently span several petabytes). So large part of the answer is "we never implemented this because we didn't really need it"
3. While eopatches and xarrays might be a bit similar, eopatches and dataframes use a very different approach. This does not mean such conversions are not possible or not useful, it is just that they are non-canonical, and there is no inherently 'right' approach for this. To showcase some of this problem, imagine you have an eopatch with a temporal feature and one timeless feature. Should this result in two separate dataframes? Do we inflate the timeless feature to be a temporally-constant one and include it in the dataframe? it really depends on what you need it for.

So at this point we consider such converters to be the responsibility of the users, because we do not have enough insight on what the 'right' conversion would be. But if such features become more sought after, we will consider adding them.

**Comment by idantene** [comment]
I understand - thanks again for the detailed answer!

One point of interest, if I may still, is that xarray offers its own conversion methods to DataFrames. To me, that suggests that eolearn can potentially support a conversion method to xarray, and ignore the pandas conversion, since it's available in xarray and has its own "native" answer to the uncertainties you raised in (3).

We anyway ended up lifting the code from 1.3.1 for this conversion in the meantime.

**Comment by zigaLuksic** [comment]
> One point of interest, if I may still, is that xarray offers its own conversion methods to DataFrames. To me, that suggests that eolearn can potentially support a conversion method to xarray, and ignore the pandas conversion, since it's available in xarray and has its own "native" answer to the uncertainties you raised in (3).

Sadly xarray is the problematic one, since it brings in an extra dependency. But might be worthwhile if there is a need for it.

> We anyway ended up lifting the code from 1.3.1 for this conversion in the meantime.

Probably the easiest solution for now. Even if we decide to add something like this, it could take a while :)

**Comment by mlubej** [comment]
Closing for now, as there is no plan in the near future to tackle this and users are encouraged to make they own solution which suits their specific needs.
